from queue import LifoQueue
stack = LifoQueue (maxsize = 3)
print(stack.qsize())
stack.put('a')
stack.put('b')
stack.put('c')
print('\n elements popded from the stack:')
print(stack.get())
print(stack.get())
print('\n empty:', stack.empty())