from collections import deque
queue = deque()
queue.append("a")
queue.append("b")
queue.append("d")
queue.append("c")
print(queue)
print(queue.pop())
print(queue.pop())
print(queue)
queue.extendleft([1,2,3,4,5,6,7])
print(queue)
queue.insert(5,6)
print(queue)
queue.remove(3)
print(queue)
